//
// Created by Charles-Eugene Loubao on 4/26/16.
//

#ifndef DRAGON_BALL_Z_RPG_EDITION_MOVETYPES_H
#define DRAGON_BALL_Z_RPG_EDITION_MOVETYPES_H

const int PRIORITY_STATE_CHANGE = 0;
const int PRIORITY_TYPE_NORMAL = PRIORITY_STATE_CHANGE + 1;

#endif //DRAGON_BALL_Z_RPG_EDITION_MOVETYPES_H
